services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: studybuddy-db
          property: connectionString

databases:
  - name: studybuddy-db
    databaseName: studybuddy
    plan: free
